### ISSUE TITLE
allows addition of empty aliases

### ISSUE THREAD

**Issue by sevu** [TheNiteCoder/mx-bashrc-config#11]
If one clicks the add button, but doesn't fill the new fields, then a line such as `alias =''` is added to ~/.bash_aliases.

After restarting the app this entry will not be listed anymore, so one cannot remove the error without editing the file by hand.

Verifying whether any of the two fields is empty at creation time would prevent this.

**Comment by TheNiteCoder** [comment]
Fixed with commit 9e32e1a
